### ISSUE TITLE
Accept Arabic numeral inputs

### ISSUE THREAD

**Issue by ghost** [hnec-vr/ocvr#13]
So on the NID submission page and on the additional info page where a user submits their family book record number, we need to accept and read Arabic numerals. We've done this in the SMS tool using unicode/utf-8. They read from left to right so we only need to make sure we encode the submission in unicode, convert to Western Arabic (numbers used in english) and compare to the API.

For the Family Book Record Number we can store this in the db as Western Arabic (english numbers) and display in admin panel this way too.

Check out Eastern Arabic Numerals here: http://en.wikipedia.org/wiki/Eastern_Arabic_numerals

**Comment by ghost** [comment]
currently, if you submit Family Book Record Number in Eastern Arabic, it displays in the Admin panel as '0'.

currently, if you enter your NID using Easter Arabic, it gives a generic error: https://www.dropbox.com/s/fqta8oq2532s8l6/Screenshot%202013-10-26%2013.08.33.png

**Comment by abinoda** [comment]
For the family book record number, I'll just convert the database field to a string column.

For the NID submission page... I'll figure it out :smile:

**Comment by abinoda** [comment]
https://github.com/hnec-vr/ocvr/commit/969e036539d29e46d883dee409ffe8f8e1831743
