### ISSUE TITLE
Email language check

### ISSUE THREAD

**Issue by ghost** [hnec-vr/ocvr#15]
make sure english in emails matches the doc i sent a couple of weeks back...link to the doc below

https://www.dropbox.com/s/a8be5znl7xhyh8j/HNEC%20OCV%20-%20Automated%20Emails%2C%20English_Arabic%20%281%29.xlsx

**Comment by abinoda** [comment]
AFAIK it should match exactly... can you re-open an issue if you notice a discrepancy?
