### ISSUE TITLE
airbrake alert for captcha

### ISSUE THREAD

**Issue by ghost** [hnec-vr/ocvr#17]
Airbrake alert: 

An error has just occurred. View full details at:
https://api.heroku.com/myapps/app18742104@heroku.com/addons/airbrake:developer?url=https%3A%2F%2Fherokuapp18742104herokucom.airbrake.io%2Fprojects%2F93410%2Fgroups%2F69508244
Error Message:
Errno::ENOENT: No such file or directory - /tmp/simple_captcha20131202-2-33bx6q.jpg

Where:
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/bundler/gems/simple-captcha-3557b78feb5f/lib/simple_captcha/middleware.rb, line 53

URL:
https://voteabroad.ly/simple_captcha?code=373b0de112f3cce20615dca242c4a3005c9d224c&time=1385958371

**Comment by jlev** [comment]
looks like a temporary error. lmk if you can reproduce
