### ISSUE TITLE
need to lock account after multiple NID attempts

### ISSUE THREAD

**Issue by ghost** [hnec-vr/ocvr#9]
and send accompanying email with "we detected some unusual activity on your account..."

**Comment by ghost** [comment]
now it has the "4 hour" suspension. need to update this to locking the account permanently.

**Comment by abinoda** [comment]
I'm a little bit confused. Isn't the escalation level:
1. require captcha after 2nd attempt
2. suspend account for n hours after 5th attempt

What practical purpose does locking the account serve? The person could just create another account if they are being intentional.
